pipeline {
    agent none
    stages {
        stage('build') {
            agent {
                docker {
                    image 'python:alpine'
                    args '--user root'
                }
            }
            when { 
                changeset "**/vote/**" 
            }
            steps {
                echo 'Compile vote app'
                dir('vote') {
                    sh 'pip install -r requirements.txt'
                }
                
            }
        }
        stage('test') {
            agent {
                docker {
                    image 'python:alpine'
                    args '--user root'
                }
            }
            when { 
                changeset "**/vote/**" 
            }
            steps {
                echo 'Running Unit Tests on vote app'
                dir('vote') {
                    sh 'pip install -r requirements.txt'
                    sh 'nosetests -v'
                }
            }
        }
        stage('docker-package') {
            agent any
            when { 
                changeset "**/vote/**" 
                branch 'master'
            }
            steps {
                echo 'Packaging worker app with docker'
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'docker-creds') {
                        def workerImage = docker.build("lenodar/vote:v${env.BUILD_ID}", "./vote")
                        workerImage.push()
                        workerImage.push("${env.BRANCH_NAME}")
                    }
                }
            }
        }
        
    }
    post {
        always {
            echo 'Pipline for vote is complete...'
        }
        failure {
            office365ConnectorSend webhookUrl: 'https://venturecorporate.webhook.office.com/webhookb2/07e4c0f5-3d39-4dce-99a6-a04e14e2de3a@0a34c976-4d3f-4f45-93c4-6f7932cf637d/IncomingWebhook/eaee1e4279dd40aeaca768a4a00bb86f/76a2818f-6409-4b87-b582-8b4a7d0a9826',
                message: "The building process failed so hard I cant even tell you right now - ${env.JOB_NAME} ${env.BUILD_NUMBER}",
                status: 'Failed'
        }
        success {
            office365ConnectorSend webhookUrl: 'https://venturecorporate.webhook.office.com/webhookb2/07e4c0f5-3d39-4dce-99a6-a04e14e2de3a@0a34c976-4d3f-4f45-93c4-6f7932cf637d/IncomingWebhook/eaee1e4279dd40aeaca768a4a00bb86f/76a2818f-6409-4b87-b582-8b4a7d0a9826',
                message: 'OMG youre such a pro! The build was a complete success',
                status: 'Success'
        }
    }
}