version: "3.7"

volumes:
  db-data:

networks:
  instavote:
    driver: bridge

services:
  vote:
    image: lenodar/vote:lastest
    build: ./vote
    ports:
      - 5002:80
    depends_on:
      - redis
    networks:
      - instavote

  redis:
    image: redis:alpine
    networks:
      - instavote

  db:
    image: postgres:9.4
    environment:
      - POSTGRESS_PASSWORD=Almafa12
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - "db-data:/var/lib/postgres/data"
    networks:
      - instavote

  result:
    image: lenodar/result:lastest
    build: ./result
    ports:
      - 5001:4000
    depends_on:
      - redis
    networks:
      - instavote

  worker:
    image: lenodar/worker:lastest
    build: ./worker
    depends_on:
      - redis
      - db
    networks:
      - instavote
