pipeline {
    agent any
    tools {
        maven 'Maven 3.8.4'
    }

    stages {
        stage('build') {
            steps {
                echo 'Compile worker app'
                dir('worker') {
                    sh 'mvn compile'
                }
                
            }
        }
        stage('test') {
            steps {
                echo 'Running Unit Tests on Worker app'
                
            }
        }
        stage('package') {
            steps {
                echo 'Packaging worker app'
                
            }
        }
    }
    post {
        always {
            echo 'Build pipeline for worker is complete...'
        }
    }
}